Vagrant.configure("2") do |config|
  config.vm.define "adminoleg" do |adminoleg|
    adminoleg.vm.hostname = "adminoleg"
    adminoleg.vm.box = "ubuntu/focal64"
    adminoleg.vm.network "private_network", ip: "192.168.33.10"
    adminoleg.vm.network "forwarded_port", guest: 80, host: 8888


    adminoleg.vm.provider "virtualbox" do |vb|
      vb.name = "adminoleg"
      vb.gui = false
      vb.memory = "1024"
    end

    adminoleg.vm.provision "shell", run: "always",  inline: <<-SHELL
        echo "Hello from the Ubuntu VM"
        sudo useradd -m  -p 1 adminuser
        sudo usermod -a -G admin adminuser
        sudo useradd -m poweruser
        sudo passwd -d poweruser
        echo 'poweruser ALL=(ALL) NOPASSWD: /usr/sbin/iptables' | sudo EDITOR='tee -a' visudo
        sudo usermod -a -G adminuser poweruser
        sudo ln -s /etc/mtab /home/poweruser/mylink
    SHELL
  end
  
end